export type SlashCommandSuggestion = {
  command: string
  title: string
  description: string
  icon: string
}

const command = (
  commandName: string,
  title: string,
  description: string,
  icon = '○',
): SlashCommandSuggestion => ({
  command: commandName,
  title,
  description,
  icon,
})

export const slashCommands: SlashCommandSuggestion[] = [
  command('/add-dir', '添加目录', '添加一个新的工作目录', '⌁'),
  command('/agents', '智能体', '管理智能体配置', '◉'),
  command('/artifacts', '产物', '列出本会话上传的 HTML 产物', '▣'),
  command('/assistant', '助手面板', '打开 Kairos assistant 面板', '✦'),
  command('/autofix-pr', '自动修 PR', '自动修复 Pull Request 的 CI 失败', '✓'),
  command('/autonomy', '自主运行', '查看自动自主运行记录', '◌'),
  command('/branch', '创建分支', '从当前对话创建一个分支', '⎇'),
  command('/break-cache', '打破缓存', '让接下来的 API 请求绕过提示缓存', '↯'),
  command('/brief', '简报模式', '切换 brief-only 模式', '▤'),
  command('/btw', '顺便问', '提出一个不打断主线的旁路问题', '?'),
  command('/buddy', '宠物', '管理桌面编码伙伴', '☼'),
  command('/clear', '清空对话', '清空对话历史并释放上下文', '＋'),
  command('/color', '颜色', '设置本会话提示栏颜色', '◐'),
  command('/commit', '提交', '创建一个 Git commit', '⌁'),
  command('/commit-push-pr', '提交并建 PR', '提交、推送并打开 Pull Request', '⇪'),
  command('/compact', '压缩', '压缩聊天上下文，保留摘要信息', '▤'),
  command('/config', '配置中心', '打开 SuperWork 桌面配置中心', '⚙'),
  command('/config model', '模型配置', '打开桌面模型配置页', '◈'),
  command('/config memory', '记忆配置', '打开桌面记忆配置页', '▣'),
  command('/config mcp', 'MCP 配置', '打开桌面 MCP 配置页', '⌘'),
  command('/config plugins', '插件配置', '打开桌面插件配置页', '◒'),
  command('/config skills', 'Skill 配置', '打开桌面 Skill 配置页', '✧'),
  command('/context', '上下文', '显示当前上下文使用情况', '◷'),
  command('/coordinator', '协调器', '切换 coordinator 协调模式', '◎'),
  command('/copy', '复制', '复制 Claude 的上一条回复到剪贴板', '⧉'),
  command('/daemon', '守护进程', '管理后台会话和 daemon', '◍'),
  command('/debug-tool-call', '调试工具', '显示最近的工具调用配对记录', '⌕'),
  command('/diff', '代码审查', '查看未提交更改，并与某个分支比较', '⌁'),
  command('/doctor', '诊断', '诊断 SuperWork 安装和设置', '⊕'),
  command('/effort', '推理强度', '设置模型使用的推理强度', '↯'),
  command('/env', '环境', '显示环境、运行时和功能开关', '▧'),
  command('/exit', '退出', '退出 REPL', '×'),
  command('/export', '导出', '导出当前对话', '⇩'),
  command('/feedback', '反馈', '发送有关 SuperWork 的反馈', '▱'),
  command('/goal', '目标', '设置或查看自动连续执行目标', '◎'),
  command('/help', '帮助', '显示帮助和可用命令', '?'),
  command('/hooks', 'Hooks', '查看工具事件 Hook 配置', '⌬'),
  command('/ide', 'IDE', '管理 IDE 集成和状态', '⌘'),
  command('/init', '初始化', '创建包含 SuperWork 说明的 AGENTS.md 文件', '▣'),
  command('/init-verifiers', '初始化验证器', '创建 verifier skills', '✓'),
  command('/insights', '洞察', '生成会话分析报告', '◷'),
  command('/issue', 'Issue', '通过 gh CLI 创建 GitHub Issue', '⊕'),
  command('/job', '任务模板', '管理模板任务', '▤'),
  command('/keybindings', '快捷键', '打开或创建快捷键配置', '⌨'),
  command('/lang', '语言', '设置显示语言', '文'),
  command('/last30days', '近 30 天', '研究某个主题的近期讨论', '◷'),
  command('/local-memory', '本地记忆', '管理本地记忆存储', '▣'),
  command('/local-vault', '本地密钥库', '管理本地加密密钥', '◈'),
  command('/login', '登录', '使用 Anthropic 账号登录', '→'),
  command('/logout', '退出登录', '退出当前配置的账号', '←'),
  command('/mcp', 'MCP', '显示 MCP 服务器状态', '⌘'),
  command('/mcp list', 'MCP 列表', '通过 SuperWork 列出 MCP 服务器', '⌘'),
  command('/memory', '记忆', '通过 SuperWork 编辑记忆文件', '▣'),
  command('/mobile', '移动端', '显示 Claude 移动 App 二维码', '▥'),
  command('/mode', '模式', '切换交互模式', '◐'),
  command('/model', '模型', '通过 SuperWork 设置或查看 AI 模型', '◈'),
  command('/monitor', '监控', '启动后台 shell 监控', '◌'),
  command('/onboarding', '引导', '重新运行首次启动设置', '□'),
  command('/perf-issue', '性能快照', '捕获性能和 token 使用快照', '↯'),
  command('/permissions', '权限', '管理工具允许和拒绝规则', '◉'),
  command('/plan', '计划', '启用计划模式或查看当前计划', '▤'),
  command('/plugin', '插件', '管理 SuperWork 插件', '◒'),
  command('/plugin list', '插件列表', '通过 SuperWork 列出插件', '◒'),
  command('/poor', '省钱模式', '切换 token 节省模式', '◍'),
  command('/pr-comments', 'PR 评论', '获取 GitHub Pull Request 评论', '▱'),
  command('/proactive', '主动模式', '切换主动自主模式', '↯'),
  command('/provider', '提供商', '切换 API provider', '◈'),
  command('/recap', '回顾', '生成一行会话回顾', '◷'),
  command('/release-notes', '发布说明', '查看发布说明', '▤'),
  command('/reload-plugins', '重载插件', '激活待生效的插件变更', '↻'),
  command('/rename', '重命名', '重命名当前对话', '✎'),
  command('/resume', '继续对话', '恢复之前的对话', '↳'),
  command('/review', '审查', '审查 Pull Request', '⌕'),
  command('/rewind', '回退', '将代码或对话恢复到之前的位置', '↶'),
  command('/security-review', '安全审查', '审查待提交变更中的安全问题', '◈'),
  command('/share', '分享', '上传当前会话日志到 GitHub Gist', '⇪'),
  command('/skill-search', 'Skill 搜索', '控制自动 Skill 匹配', '✧'),
  command('/skills', 'Skills', '列出可用 Skills', '✧'),
  command('/skill list', 'Skill 列表', '通过 SuperWork 列出 Skills', '✧'),
  command('/status', '状态', '显示 SuperWork 状态', '◉'),
  command('/statusline', '状态栏', '设置 SuperWork 状态栏 UI', '▔'),
  command('/stickers', '贴纸', '订购 SuperWork 贴纸', '◇'),
  command('/summary', '摘要', '生成并显示会话摘要', '▤'),
  command('/tasks', '任务', '列出并管理后台任务', '☑'),
  command('/teleport', '传送', '从 claude.ai 恢复 SuperWork 会话', '↬'),
  command('/terminal-setup', '终端设置', '安装终端快捷键绑定', '⌨'),
  command('/theme', '主题', '更改主题', '◐'),
  command('/tui', 'TUI', '切换无闪烁 TUI 模式', '▥'),
  command('/ultraplan', '高级计划', '在 SuperWork Web 上草拟高级计划', '▤'),
  command('/ultrareview', '高级审查', '在 SuperWork Web 上查找并验证问题', '⌕'),
  command('/usage', '用量', '显示会话成本、套餐用量和活动统计', '◷'),
  command('/version', '版本', '打印当前运行版本', 'ⓘ'),
  command('/vim', 'Vim', '切换 Vim 编辑模式', '⌨'),
  command('/Viral Writer', '爆款写作', '自媒体内容创作工具', '✎'),
  command('/voice', '语音', '切换语音模式', '◉'),
  command('/web-tools', 'Web 工具', '配置网页搜索和网页抓取后端', '⌕'),
  command('/wewrite', '公众号写作', '微信公众号内容全流程助手', '✎'),
  command('/workflows', '工作流', '打开工作流监控面板', '☷'),
]

export function slashSuggestions(input: string): SlashCommandSuggestion[] {
  if (!input.startsWith('/')) return []
  const query = input.toLowerCase()
  return slashCommands.filter(item => item.command.toLowerCase().startsWith(query))
}

export function selectedSlashCommand(input: string): SlashCommandSuggestion | null {
  return slashCommands.find(item => item.command === input.trim()) ?? null
}
