export type SlashCommandSuggestion = {
  command: string
  title: string
  description: string
}

const command = (
  commandName: string,
  title: string,
  description: string,
): SlashCommandSuggestion => ({
  command: commandName,
  title,
  description,
})

export const slashCommands: SlashCommandSuggestion[] = [
  command('/add-dir', 'Add directory', 'Add a new working directory'),
  command('/agents', 'Agents', 'Manage agent configurations'),
  command('/artifacts', 'Artifacts', 'List HTML artifacts uploaded in this session'),
  command('/assistant', 'Assistant', 'Open the Kairos assistant panel'),
  command('/autofix-pr', 'Autofix PR', 'Auto-fix CI failures on a pull request'),
  command('/autonomy', 'Autonomy', 'Inspect automatic autonomy runs'),
  command('/branch', 'Branch', 'Create a branch of the current conversation'),
  command('/break-cache', 'Break cache', 'Force upcoming API calls to miss prompt cache'),
  command('/brief', 'Brief', 'Toggle brief-only mode'),
  command('/btw', 'BTW', 'Ask a side question without interrupting the main conversation'),
  command('/buddy', 'Buddy', 'Manage the coding companion'),
  command('/clear', 'Clear', 'Clear conversation history and free context'),
  command('/color', 'Color', 'Set prompt bar color for this session'),
  command('/commit', 'Commit', 'Create a git commit'),
  command('/commit-push-pr', 'Commit PR', 'Commit, push, and open a PR'),
  command('/compact', 'Compact', 'Compact conversation history while keeping summary context'),
  command('/config', '配置中心', '打开 SuperWork 桌面配置中心'),
  command('/config model', '模型配置', '打开桌面模型配置页'),
  command('/config memory', '记忆配置', '打开桌面记忆配置页'),
  command('/config mcp', 'MCP 配置', '打开桌面 MCP 配置页'),
  command('/config plugins', '插件配置', '打开桌面插件配置页'),
  command('/config skills', 'Skill 配置', '打开桌面 Skill 配置页'),
  command('/context', 'Context', 'Show current context usage'),
  command('/coordinator', 'Coordinator', 'Toggle coordinator mode'),
  command('/copy', 'Copy', "Copy Claude's last response to clipboard"),
  command('/daemon', 'Daemon', 'Manage background sessions and daemon'),
  command('/debug-tool-call', 'Debug tools', 'Show recent tool call pairs from the session log'),
  command('/diff', 'Diff', 'View uncommitted changes and per-turn diffs'),
  command('/doctor', 'Doctor', 'Diagnose Claude Code installation and settings'),
  command('/effort', 'Effort', 'Set effort level for model usage'),
  command('/env', 'Environment', 'Show environment, runtime, and feature flags'),
  command('/exit', 'Exit', 'Exit the REPL'),
  command('/export', 'Export', 'Export the current conversation'),
  command('/feedback', 'Feedback', 'Submit feedback about Claude Code'),
  command('/goal', 'Goal', 'Set or view a persistent auto-continuation goal'),
  command('/help', 'Help', 'Show help and available commands'),
  command('/hooks', 'Hooks', 'View hook configurations for tool events'),
  command('/ide', 'IDE', 'Manage IDE integrations and status'),
  command('/init', 'Init', 'Initialize a CLAUDE.md file for this codebase'),
  command('/init-verifiers', 'Init verifiers', 'Create verifier skills'),
  command('/insights', 'Insights', 'Generate a session analysis report'),
  command('/issue', 'Issue', 'Create a GitHub issue via gh CLI'),
  command('/job', 'Jobs', 'Manage template jobs'),
  command('/keybindings', 'Keybindings', 'Open or create keybindings configuration'),
  command('/lang', 'Language', 'Set display language'),
  command('/last30days', 'Last 30 days', 'Research recent discussion about a topic'),
  command('/local-memory', 'Local memory', 'Manage local memory stores'),
  command('/local-vault', 'Local vault', 'Manage local encrypted secrets'),
  command('/login', 'Login', 'Sign in with an Anthropic account'),
  command('/logout', 'Logout', 'Sign out from the configured account'),
  command('/mcp', 'MCP', 'Manage MCP servers through Claude Code'),
  command('/mcp list', 'MCP 列表', 'List MCP servers through Claude Code'),
  command('/memory', 'Memory', 'Edit Claude memory files through Claude Code'),
  command('/mobile', 'Mobile', 'Show QR code for the Claude mobile app'),
  command('/mode', 'Mode', 'Switch interaction mode'),
  command('/model', 'Model', 'Set or view the AI model through Claude Code'),
  command('/monitor', 'Monitor', 'Start a background shell monitor'),
  command('/onboarding', 'Onboarding', 'Re-run first-run setup'),
  command('/perf-issue', 'Performance', 'Capture performance and token usage snapshot'),
  command('/permissions', 'Permissions', 'Manage allow and deny tool permission rules'),
  command('/plan', 'Plan', 'Enable plan mode or view the current plan'),
  command('/plugin', 'Plugins', 'Manage Claude Code plugins'),
  command('/plugin list', '插件列表', 'List plugins through Claude Code'),
  command('/poor', 'Poor mode', 'Toggle token-saving poor mode'),
  command('/pr-comments', 'PR comments', 'Get comments from a GitHub pull request'),
  command('/proactive', 'Proactive', 'Toggle proactive autonomous mode'),
  command('/provider', 'Provider', 'Switch API provider'),
  command('/recap', 'Recap', 'Generate a one-line session recap'),
  command('/release-notes', 'Release notes', 'View release notes'),
  command('/reload-plugins', 'Reload plugins', 'Activate pending plugin changes'),
  command('/rename', 'Rename', 'Rename the current conversation'),
  command('/resume', 'Resume', 'Resume a previous conversation'),
  command('/review', 'Review', 'Review a pull request'),
  command('/rewind', 'Rewind', 'Restore code and/or conversation to a previous point'),
  command('/security-review', 'Security review', 'Review pending changes for security issues'),
  command('/share', 'Share', 'Upload the current session log to GitHub Gist'),
  command('/skill-search', 'Skill search', 'Control automatic skill matching'),
  command('/skills', 'Skills', 'List available skills'),
  command('/skill list', 'Skill 列表', 'List skills through Claude Code'),
  command('/status', 'Status', 'Show Claude Code status'),
  command('/statusline', 'Status line', 'Set up Claude Code status line UI'),
  command('/stickers', 'Stickers', 'Order Claude Code stickers'),
  command('/summary', 'Summary', 'Generate and display a session summary'),
  command('/tasks', 'Tasks', 'List and manage background tasks'),
  command('/teleport', 'Teleport', 'Resume a Claude Code session from claude.ai'),
  command('/terminal-setup', 'Terminal setup', 'Install terminal key bindings'),
  command('/theme', 'Theme', 'Change the theme'),
  command('/tui', 'TUI', 'Toggle flicker-free TUI mode'),
  command('/ultraplan', 'Ultraplan', 'Draft an advanced plan on Claude Code web'),
  command('/ultrareview', 'Ultrareview', 'Find and verify bugs on Claude Code web'),
  command('/usage', 'Usage', 'Show session cost, plan usage, and activity stats'),
  command('/version', 'Version', 'Print the running version'),
  command('/vim', 'Vim', 'Toggle Vim editing mode'),
  command('/Viral Writer', 'Viral Writer', '自媒体内容创作工具'),
  command('/voice', 'Voice', 'Toggle voice mode'),
  command('/web-tools', 'Web tools', 'Configure web search and web fetch backends'),
  command('/wewrite', 'Wewrite', '微信公众号内容全流程助手'),
  command('/workflows', 'Workflows', 'Open workflow monitoring panel'),
]

export function slashSuggestions(input: string): SlashCommandSuggestion[] {
  if (!input.startsWith('/')) return []
  const query = input.toLowerCase()
  return slashCommands.filter(item => item.command.toLowerCase().startsWith(query))
}

export function selectedSlashCommand(input: string): SlashCommandSuggestion | null {
  return slashCommands.find(item => item.command === input.trim()) ?? null
}
